server:
  port: 9701
  servlet:
    context-path: /api
spring:
  application:
    name: api
  profiles:
    active: '@profileActive@'
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 200
      connection-timeout: 12000
      idle-timeout: 10000
      max-lifetime: 1000
      minimum-idle: 10
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      jdbc:
        batch_size: 30
  jackson:
    serialization:
      INDENT_OUTPUT: true
  main:
    allow-bean-definition-overriding: true
thread:
  pool:
    corePoolSize: 10
    maxPoolSize: 50
    keepAliveSeconds: 5
    queueCapacity: 512
    waitForTasksToCompleteOnShutdown: true
    awaitTerminationSeconds: 60
currency:
  api:
    key:
